"""Third-party companion apps that make Plex more useful, set up with Docker Compose.

- Tautulli (http://localhost:8181): who watched what, play history, stats, and alerts when
  a stream buffers or the server goes down.
- Kometa (formerly Plex Meta Manager): builds collections automatically (franchises like
  "Marvel Cinematic Universe", IMDb Top 250, Trending, genres, decades) and can badge
  posters with 4K/HDR. It only changes Plex metadata, never your files.
- Plex Auto Languages: when you switch a show's audio or subtitle track, it switches every
  other episode of that show to match.
- PlexTraktSync: backs up watch history and ratings to Trakt.tv (free account) and marks
  things watched there as you watch, so a future rebuild never loses them.

The generated folder holds your Plex token and TMDB key, so it lives outside the repo.
Personal libraries (Home Videos, photos) are never handed to Kometa.
"""
import json
from pathlib import Path

MOVIE_COLLECTIONS = ["basic", "tmdb", "imdb", "franchise", "universe", "genre", "decade", "seasonal"]
SHOW_COLLECTIONS = ["basic", "tmdb", "imdb", "network", "genre"]
OVERLAYS = ["resolution", "audio_codec"]


def media_libraries(sections):
    """Movie/TV libraries matched by the Plex agents. Skips Home Videos and anything personal."""
    out = []
    for s in sections:
        if s.get("type") not in ("movie", "show"):
            continue
        if not s.get("agent", "").startswith(("tv.plex.agents.", "com.plexapp.agents.themoviedb",
                                              "com.plexapp.agents.imdb", "com.plexapp.agents.thetvdb")):
            continue
        if any(w in s.get("title", "").lower() for w in ("home", "personal", "family", "phone", "camera")):
            continue
        out.append(s)
    return out


def _q(s):
    return json.dumps(str(s))  # a JSON string is a valid YAML scalar


def kometa_config(sections, plex_url, token, tmdb_key, overlays=False):
    lines = ["# Generated by plexopt plex-companions. Docs: https://kometa.wiki", "libraries:"]
    for s in media_libraries(sections):
        lines.append(f"  {_q(s['title'])}:")
        lines.append("    collection_files:")
        for d in MOVIE_COLLECTIONS if s["type"] == "movie" else SHOW_COLLECTIONS:
            lines.append(f"      - default: {d}")
        if overlays:
            lines.append("    overlay_files:")
            lines += [f"      - default: {d}" for d in OVERLAYS]
        else:
            lines.append("    # overlay_files:            # badges posters with 4K / HDR / Atmos")
            lines += [f"    #   - default: {d}" for d in OVERLAYS]
    lines += [
        "settings:",
        "  cache: true",
        "  minimum_items: 3             # don't create tiny collections",
        "  delete_below_minimum: true",
        "  run_again_delay: 2",
        "plex:",
        f"  url: {_q(plex_url)}",
        f"  token: {_q(token)}",
        "  timeout: 120",
        "  clean_bundles: false         # plexopt plex-refresh does housekeeping",
        "  empty_trash: false",
        "  optimize: false",
        "tmdb:",
        f"  apikey: {_q(tmdb_key)}",
        "  language: en",
        "",
    ]
    return "\n".join(lines)


def env_file(tz, token, plex_url):
    return f"TZ={tz}\nPLEX_URL={plex_url}\nPLEX_TOKEN={token}\n"


def compose(kometa_time="04:00"):
    return f"""# Generated by plexopt plex-companions. Settings (time zone, Plex token) are in .env
# Start:  docker compose up -d        Stop: docker compose down
# Plex itself runs natively on this PC; the containers reach it at host.docker.internal:32400.
x-common: &common
  restart: unless-stopped
  extra_hosts: ["host.docker.internal:host-gateway"]

services:
  tautulli:
    <<: *common
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    ports: ["8181:8181"]
    environment: {{TZ: "${{TZ}}"}}
    volumes: ["./tautulli:/config"]

  kometa:
    <<: *common
    image: kometateam/kometa:latest
    container_name: kometa
    environment: {{TZ: "${{TZ}}", KOMETA_TIMES: {_q(kometa_time)}}}
    volumes: ["./kometa:/config"]

  plex-auto-languages:
    <<: *common
    image: remirigal/plex-auto-languages:latest
    container_name: plex-auto-languages
    environment: {{TZ: "${{TZ}}", PLEX_URL: "${{PLEX_URL}}", PLEX_TOKEN: "${{PLEX_TOKEN}}"}}
    volumes: ["./plex-auto-languages:/config"]

  # Needs a one-time Trakt login first (README step 5); until then it just restarts quietly.
  plextraktsync:
    <<: *common
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    command: watch
    environment: {{TZ: "${{TZ}}"}}
    volumes: ["./plextraktsync:/app/config"]
"""


README = """PlexOptimize companion apps
===========================

This folder contains your Plex token (.env) and TMDB key (kometa/config.yml).
Don't share it or put it in git.

1. Install Docker Desktop (Windows: winget install Docker.DockerDesktop), start it once.
2. In this folder:  docker compose up -d
3. Tautulli: open http://localhost:8181 and follow the wizard.
   Plex IP/hostname: host.docker.internal   Port: 32400   then "Verify".
4. Kometa builds collections every night at {time}. To run it right now:
     docker compose run --rm kometa --run
   Then look at the "Collections" tab of each library in Plex.
   To change which collections you get, edit kometa/config.yml (https://kometa.wiki/en/latest/defaults/guide/).
   To badge posters with 4K/HDR, uncomment overlay_files there. To take the badges off again,
   add "remove_overlays: true" under that library in config.yml and run Kometa once more.
5. PlexTraktSync (watch-history backup). One-time setup:
   a. Make a free account at https://trakt.tv, then create an "app" at
      https://trakt.tv/oauth/applications/new  (name: PlexTraktSync,
      redirect uri: urn:ietf:wg:oauth:2.0:oob). Keep its Client ID and Client Secret handy.
   b. Run:  docker compose run --rm plextraktsync login
      Answer its questions: Plex username/password, pick your server, then the Trakt
      Client ID/Secret and the code it shows. If it asks for the server URL, use
      http://host.docker.internal:32400
   c. First full sync:  docker compose run --rm plextraktsync sync
   d. docker compose up -d   (from now on it updates Trakt live as you watch)
6. Plex Auto Languages needs nothing. Change a show's audio or subtitles once in any
   Plex app and it switches the rest of that show's episodes to match.
"""


def write(out_dir, sections, token, tmdb_key, tz="Etc/UTC", overlays=False,
          plex_url="http://host.docker.internal:32400", force=False, log=print):
    out = Path(out_dir).expanduser()
    (out / "kometa").mkdir(parents=True, exist_ok=True)
    for d in ("tautulli", "plex-auto-languages", "plextraktsync"):
        (out / d).mkdir(exist_ok=True)
    libs = media_libraries(sections)
    if not libs:
        log("[!] No Movies/TV libraries found in Plex yet - run plexopt plex-setup first.")
    files = {
        out / "docker-compose.yml": compose(),
        out / ".env": env_file(tz, token, plex_url),
        out / "kometa" / "config.yml": kometa_config(sections, plex_url, token, tmdb_key, overlays),
        out / "README.txt": README.format(time="04:00"),
    }
    for path, text in files.items():
        if path.exists() and not force and path.name == "config.yml":
            log(f"[keep] {path} already exists (use --force to overwrite your edits)")
            continue
        path.write_text(text, encoding="utf-8")
        log(f"[wrote] {path}")
    skipped = [s["title"] for s in sections if s not in libs]
    log(f"Kometa will manage: {', '.join(s['title'] for s in libs) or 'nothing yet'}")
    if skipped:
        log(f"Left alone (personal/other): {', '.join(skipped)}")
    return out
