"""Third-party companion apps that make Plex more useful, set up with Docker Compose.

- Tautulli (http://localhost:8181): who watched what, play history, stats, and alerts when
  a stream buffers or the server goes down.
- Kometa (formerly Plex Meta Manager): builds collections automatically (franchises like
  "Marvel Cinematic Universe", IMDb Top 250, Trending, genres, decades) and can badge
  posters with 4K/HDR. It only changes Plex metadata, never your files.

The generated folder holds your Plex token and TMDB key, so it lives outside the repo.
Personal libraries (Home Videos, photos) are never handed to Kometa.
"""
import json
from pathlib import Path

MOVIE_COLLECTIONS = ["basic", "tmdb", "imdb", "franchise", "universe", "genre", "decade", "seasonal"]
SHOW_COLLECTIONS = ["basic", "tmdb", "imdb", "network", "genre"]
OVERLAYS = ["resolution", "audio_codec"]


def media_libraries(sections):
    """Movie/TV libraries matched by the Plex agents. Skips Home Videos and anything personal."""
    out = []
    for s in sections:
        if s.get("type") not in ("movie", "show"):
            continue
        if not s.get("agent", "").startswith(("tv.plex.agents.", "com.plexapp.agents.themoviedb",
                                              "com.plexapp.agents.imdb", "com.plexapp.agents.thetvdb")):
            continue
        if any(w in s.get("title", "").lower() for w in ("home", "personal", "family", "phone", "camera")):
            continue
        out.append(s)
    return out


def _q(s):
    return json.dumps(str(s))  # a JSON string is a valid YAML scalar


def kometa_config(sections, plex_url, token, tmdb_key, overlays=False):
    lines = ["# Generated by plexopt plex-companions. Docs: https://kometa.wiki", "libraries:"]
    for s in media_libraries(sections):
        lines.append(f"  {_q(s['title'])}:")
        lines.append("    collection_files:")
        for d in MOVIE_COLLECTIONS if s["type"] == "movie" else SHOW_COLLECTIONS:
            lines.append(f"      - default: {d}")
        if overlays:
            lines.append("    overlay_files:")
            lines += [f"      - default: {d}" for d in OVERLAYS]
        else:
            lines.append("    # overlay_files:            # badges posters with 4K / HDR / Atmos")
            lines += [f"    #   - default: {d}" for d in OVERLAYS]
    lines += [
        "settings:",
        "  cache: true",
        "  minimum_items: 3             # don't create tiny collections",
        "  delete_below_minimum: true",
        "  run_again_delay: 2",
        "plex:",
        f"  url: {_q(plex_url)}",
        f"  token: {_q(token)}",
        "  timeout: 120",
        "  clean_bundles: false         # plexopt plex-refresh does housekeeping",
        "  empty_trash: false",
        "  optimize: false",
        "tmdb:",
        f"  apikey: {_q(tmdb_key)}",
        "  language: en",
        "",
    ]
    return "\n".join(lines)


def compose(tz, kometa_time="04:00"):
    return f"""# Generated by plexopt plex-companions.
# Start:  docker compose up -d        Stop: docker compose down
# Plex itself runs natively on this PC; the containers reach it at host.docker.internal:32400.
services:
  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    ports: ["8181:8181"]
    environment: {{TZ: {_q(tz)}}}
    volumes: ["./tautulli:/config"]
    extra_hosts: ["host.docker.internal:host-gateway"]

  kometa:
    image: kometateam/kometa:latest
    container_name: kometa
    restart: unless-stopped
    environment: {{TZ: {_q(tz)}, KOMETA_TIMES: {_q(kometa_time)}}}
    volumes: ["./kometa:/config"]
    extra_hosts: ["host.docker.internal:host-gateway"]
"""


README = """PlexOptimize companion apps
===========================

This folder contains your Plex token and TMDB key. Don't share it or put it in git.

1. Install Docker Desktop (Windows: winget install Docker.DockerDesktop), start it once.
2. In this folder:  docker compose up -d
3. Tautulli: open http://localhost:8181 and follow the wizard.
   Plex IP/hostname: host.docker.internal   Port: 32400   then "Verify".
4. Kometa builds collections every night at {time}. To run it right now:
     docker compose run --rm kometa --run
   Then look at the "Collections" tab of each library in Plex.
   To change which collections you get, edit kometa/config.yml (https://kometa.wiki/en/latest/defaults/guide/).
   To badge posters with 4K/HDR, uncomment overlay_files there. To take the badges off again,
   add "remove_overlays: true" under that library in config.yml and run Kometa once more.
"""


def write(out_dir, sections, token, tmdb_key, tz="Etc/UTC", overlays=False,
          plex_url="http://host.docker.internal:32400", force=False, log=print):
    out = Path(out_dir).expanduser()
    (out / "kometa").mkdir(parents=True, exist_ok=True)
    (out / "tautulli").mkdir(exist_ok=True)
    libs = media_libraries(sections)
    if not libs:
        log("[!] No Movies/TV libraries found in Plex yet - run plexopt plex-setup first.")
    files = {
        out / "docker-compose.yml": compose(tz),
        out / "kometa" / "config.yml": kometa_config(sections, plex_url, token, tmdb_key, overlays),
        out / "README.txt": README.format(time="04:00"),
    }
    for path, text in files.items():
        if path.exists() and not force and path.name != "README.txt":
            log(f"[keep] {path} already exists (use --force to overwrite your edits)")
            continue
        path.write_text(text, encoding="utf-8")
        log(f"[wrote] {path}")
    skipped = [s["title"] for s in sections if s not in libs]
    log(f"Kometa will manage: {', '.join(s['title'] for s in libs) or 'nothing yet'}")
    if skipped:
        log(f"Left alone (personal/other): {', '.join(skipped)}")
    return out
